### PR TITLE
MongoServer.BuildInfo always null at start.

### PR DESCRIPTION
**Pull request by ArtemNizelnyk**
You have to connect to the database before you can get this property.

https://jira.mongodb.org/browse/CSHARP-881

### CODE REVIEW

**Comment by olegburov** [comment]
@ArtemNizelnyk good catch!

Can you please change a code as Craig Wilson showed to make it workable with Mongo Cluster?
`buildInfos = srv.Instances.Select(x => x.BuildInfo);`

**Review by ob1dev — CHANGES_REQUESTED** [review]
@ArtemNizelnyk good catch!

Can you please change a code as Craig Wilson showed to make it workable with Mongo Cluster?
buildInfos = srv.Instances.Select(x => x.BuildInfo);

**Comment by ArtemNizelnyk** [comment]
@olegburov I've added the changes.

**Comment by ob1dev** [comment]
@ArtemNizelnyk The code fails with `NullReferenceException`, because the `BuildInfo` property is `null` for an Arbiter instance. Could you please test it using a MongoDB Cluster that includes at least 2x Nodes + 1x Arbiter. You can use a test xDB Cloud Set that PSS own. Let me know if you need credentials.

**Review by ob1dev — APPROVED** [review]

**Pull request merged**
